### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Frosxc** [NoobLovePMMP/BetterTrade#1]
bling BetterTrade v1.0.0
[06:28:24.292] [Server thread/CRITICAL]: ParseError: "Unclosed '{' on line 346 does not match ')'" (EXCEPTION) in "plugins/BetterTrade-main/src/Noob/BetterTrade/entity/VillagerTrade" at line 368
--- Stack trace ---
  #0 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[37] Noob\BetterTrade\entity\VillagerTrade)
  #1 (): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[37] Noob\BetterTrade\entity\VillagerTrade)
  #2 pmsrc/src/utils/Utils(547): class_exists(string[37] Noob\BetterTrade\entity\VillagerTrade)
  #3 pmsrc/src/entity/EntityFactory(198): pocketmine\utils\Utils::testValidInstance(string[37] Noob\BetterTrade\entity\VillagerTrade, string[24] pocketmine\entity\Entity)
  #4 plugins/BetterTrade-main/src/Noob/BetterTrade/RegisterVillager(23): pocketmine\entity\EntityFactory->register(string[37] Noob\BetterTrade\entity\VillagerTrade, object Closure#120572, array[1])
  #5 plugins/BetterTrade-main/src/Noob/BetterTrade/RegisterVillager(18): Noob\BetterTrade\RegisterVillager::registerEntities()
  #6 plugins/BetterTrade-main/src/Noob/BetterTrade/BetterTrade(33): Noob\BetterTrade\RegisterVillager::init()

**Comment by NoobLovePMMP** [comment]
Ok, I will fix it, sorry you

**Comment by NoobLovePMMP** [comment]
I fixed this error, you can redownload here ^^
<a>https://github.com/NoobLovePMMP/BetterTrade-Fixed

**Comment by Frosxc** [comment]
thanks

**Comment by Frosxc** [comment]
PocketMine-MP version: 5.17.0 [Protocol 686]
Git commit: 37bf4bc0b0c095758c8ee09e5681a369396da7ce
PHP version: 8.2.17
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BetterTrade

Thread: Main
Error: Undefined array key 0
File: plugins/BetterTrade-Fixed-main/src/Noob/BetterTrade/commands/TradeCommand
Line: 39
Type: ErrorException
Backtrace:
#0 plugins/BetterTrade-Fixed-main/src/Noob/BetterTrade/commands/TradeCommand(39): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 0, string[93] /home/container/plugins/BetterTrade-Fixed-main/src/Noob/BetterTrade/commands/Tra, int 39)
#1 pmsrc/src/command/SimpleCommandMap(212): Noob\BetterTrade\commands\TradeCommand->execute(object pocketmine\player\Player#643782, string[11] bettertrade, array[0])
#2 pmsrc/src/Server(1431): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#643782, string[11] bettertrade)
#3 pmsrc/src/player/Player(1516): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#643782, string[11] bettertrade)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(819): pocketmine\player\Player->chat(string[12] /bettertrade)
#5 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#691693)
#6 pmsrc/src/network/mcpe/NetworkSession(469): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#663594)
#7 pmsrc/src/network/mcpe/NetworkSession(407): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object 












xd

**Comment by NoobLovePMMP** [comment]
Can you contact me in Facebook or Zalo?, We can discuss to improve, I don't know exactly when your error occurred, explain specifically so I can give the next patch, thank you

**Comment by Frosxc** [comment]
the crash occurred when I typed /bettertrade

**Comment by NoobLovePMMP** [comment]
Ok that error was fixed, you can click here to download new version :3
https://github.com/NoobLovePMMP/BetterTrade-Fixed/tree/main

**Comment by Frosxc** [comment]
Thank You

**Comment by NoobLovePMMP** [comment]
A star for me :>>
